SELECT reporte FROM(

SELECT DISTINCT SAFE_CONVERT_BYTES_TO_STRING(RPAD(CAST(reporte as bytes),142)) as reporte, rank_number FROM(

SELECT 
  (CODIGO_INSTITUCION_FINANCIERA || IDENTIFICACION_ARCHIVO || FECHA) AS reporte, 1 as rank_number
FROM 
  `${project_name}.${dataset}.C78_primer_registro` 
WHERE 
  EXECUTION_DATE = (SELECT MAX(EXECUTION_DATE) FROM `${project_name}.${dataset}.C78_primer_registro`)

UNION ALL

SELECT 
  (TIPO_DE_REGISTRO ||
  NUMERO_INTERNO_IDENTIFICACION_TARJETA ||
  RUT ||
  TIPO_TARJETA ||
  CARTERA_NORMAL ||
  PROVISION_SOBRE_CARTERA_NORMAL ||
  CARTERA_EN_INCUMPLIMIENTO ||
  PROVISION_SOBRE_CARTERA_EN_INCUMPLIMIENTO ||
  DIAS_DE_MOROSIDAD ||
  PERIODO_INGRESO_DEUDOR_A_CARTERA_INCUMPLIMIENTO) AS reporte,
  2 as rank_number
FROM
 `${project_name}.${dataset}.C78_activos`
WHERE 
  EXECUTION_DATE = (SELECT MAX(EXECUTION_DATE) FROM `${project_name}.${dataset}.C78_activos`)

UNION ALL

SELECT 
  (TIPO_DE_REGISTRO ||
  NUMERO_INTERNO_IDENTIFICACION_TARJETA ||
  RUT ||
  CREDITOS_CONTINGENTE_CARTERA_NORMAL ||
  MONTO_EXPOSICION_CREDITOS_CONTINGENTES_CARTERA_NORMAL ||
  PROVISION_SOBRE_CARTERA_NORMAL ||
  CREDITOS_CONTINGENTES_CARTERA_EN_INCUMPLIMIENTO ||
  PROVISION_SOBRE_CARTERA_EN_INCUMPLIMIENTO ||
  MONTO_OTORGADO_LINEA_DE_CREDITO ||
  FECHA_DE_APERTURA ||
  FECHA_DE_ULTIMO_CUPO_APROBADO) AS reporte,
  3 as rank_number
FROM
 `${project_name}.${dataset}.C78_contingentes`
WHERE 
  EXECUTION_DATE = (SELECT MAX(EXECUTION_DATE) FROM `${project_name}.${dataset}.C78_contingentes`)

UNION ALL

SELECT 
  (TIPO_DE_REGISTRO ||
  NUMERO_INTERNO_IDENTIFICACION_TARJETA ||
  RUT ||
  TIPO_DE_PRODUCTO ||
  MONTO_DE_COLOCACION_ASOCIADA_PRODUCTO ||
  MONTO_DE_PROVISION_ASOCIADA_PRODUCTO) AS reporte,
  4 as rank_number
FROM
 `${project_name}.${dataset}.C78_tipoproducto`
WHERE 
  EXECUTION_DATE = (SELECT MAX(EXECUTION_DATE) FROM `${project_name}.${dataset}.C78_tipoproducto`)
UNION ALL
SELECT
(TIPO_DE_REGISTRO ||
  NUMERO_INTERNO_IDENTIFICACION_TARJETA ||
  RUT ||MONTO_TOTAL_FACTURADO||
  TIPO_DE_OPCION_DE_PAGO_MINIMO||
  MONTO_CANCELADO||TIPO_DE_PAGO_DE_LA_TARJETA_ROTATIVA) AS reporte,
  5 as rank_number
FROM `${project_name}.${dataset}.C78_cartera_rotativa` 
WHERE EXECUTION_DATE=(SELECT MAX(EXECUTION_DATE) FROM `${project_name}.${dataset}.C78_cartera_rotativa`)
)

)


ORDER BY rank_number